### ISSUE TITLE
Potential overflow on circular queue implementation

### ISSUE THREAD

**Issue by vicrac** [JSchaenzle/cedux#10]
I noticed that while moving `front`/`rear` (`read_idx`/`write_idx`) around in your circular queue implementation, you never actually decrement theirs value to be within array size bounds (but rather calculate `mod` each time). It can lead to overflow if many actions are getting dispatched (I noticed the very same code in your `c-message-queue` repository) - e.g. I will probably dispatch a `TIC` action every `100ms`.

**Comment by JSchaenzle** [comment]
I'm not sure that the index overflowing would cause a problem. The queue implementation does rely on the capacity being a power of two, otherwise it does cause problems.

Can you write a unit test that demonstrates the problem?

**Comment by vicrac** [comment]
@JSchaenzle I will try, could you help me set up the test? I would like to be able to simply perform basic enqueue and dequeue operations and assert on results.I've already created a file for it, could you give me a hint in there: https://github.com/vicrac/cedux/pull/1?
