### ISSUE TITLE
Add optional thread-safety

### ISSUE THREAD

**Issue by jmgregory** [JSchaenzle/cedux#5]
In a multi-threaded application, it would be nice to have some guarantee that the action queue is thread-safe.  I haven't analyzed the queue algorithm closely, but I believe there could be a race condition if a thread tries to dispatch an action while the main Cedux run thread is popping the action queue and running reducers.  This might result in actions being missed.

I propose adding a new `void *lock` member to the store object, and a lock registration function to Cedux that lets the user set three function pointers on the store: `void lock_init(void *lock)`, `void lock_acquire(void *lock)`, and `void lock_release(void *lock)`.  For portability purposes, the user would be responsible for implementing these functions (for instance, as wrappers around the `pthread_mutex_*` family).  These new members would all be `NULL` by default, and when performing operations involving the queue, Cedux would check these function pointers and only run them if not `NULL`.

The end result would be that users who want thread-safety guarantees can get them, and users who aren't worried about thread safety can simply skip the lock registration and Cedux will continue to function the way it does now (albeit with a tiny bit more overhead in the `dispatch` and `run` calls, and a slightly larger store object).

I'm happy to tackle this if you like.

**Comment by JSchaenzle** [comment]
Sounds awesome! This is something I've been thinking about adding as well but never got around to it. If you have time feel free! I like idea of the init, acquire and release methods. Do you think it's necessary/helpful for the store the store to keep the handle to the lock object?

**Comment by jmgregory** [comment]
Yeah, in the spirit of PR #2 where you can have multiple stores, I think it makes sense for each store to have it's own handle on a lock.
